### ISSUE TITLE
broken link in Guide to Statistical Power

### ISSUE THREAD

**Issue by miriamgolden** [egap/methods-guides#24]
The last word in this paragraph is not linked as it should be:

Randomization Protocol. What kind of randomization will you be employing? Simple randomization gives all subjects an equal probability of being in the treatment group, and then performs a (possibly weighted) coin flip for each. Complete randomization is similar, but it ensures that exactly a certain number will be assigned to treatment. Block randomization is even more powerful — it ensures that a certain number within a subgroup will be assigned to treatment. A restricted random assignment rejects some random assignments based on some set of criteria — lack of balance perhaps. These various types of random assignment can dramatically increase the power of an experiment at no extra cost. Read up on randomization protocols here.

**Comment by jwbowers** [comment]
Thanks much @miriamgolden! @malisi Is, I think, working on the problems of links. Glad to have one specifically pointed out. I'm assigning this issue to you, Matt, since I think you are already working on this.

**Comment by malisi** [comment]
thanks, @miriamgolden--the link to the randomization guide should be working now
