### ISSUE TITLE
page is giving 502 Bad Gateway

### ISSUE THREAD

**Issue by maartenvoors** [egap/methods-guides#33]
see https://egap.org/resource/10-things-to-know-about-multiple-comparisons/

**Comment by malisi** [comment]
Thanks for noting this, Maarten. Issue was on the side of Combinatronics (the site that turns raw git html files into formatted content). I updated each guide/standards discussion to the version of their product meant for larger file requests, and all of them now display correctly for me.

Closing the issue; please re-open if it's still giving you problems.
