### ISSUE TITLE
How to translate "potential outcomes" to Spanish?

### ISSUE THREAD

**Issue by jwbowers** [egap/methods-guides#37]
@lilymedina I think that "salida potencial" sounds weird. A couple of other folks who study causal inference and are native Spanish speakers agree. We suggest "resultado potencial" or "respuesta potencial".  However, if the rest of the non-Chilean world thinks that "salida" is best, I'd defer.

Tagging @nahomi for her knowledge.

**Comment by lilymedina** [comment]
Since more than a couple (including myself) agrees that "salida potencial" sounds odd, then I'm happy to change it. I'd prefer using "resultado potencial"

**Comment by nahomi** [comment]
Sounds like a good solution.
